### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.

### ISSUE THREAD

**Issue by kyawsanoo** [zeshuaro/google_api_headers#41]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_headers' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31

**Comment by ChinHairSaintClair** [comment]
I have run into the same issue.

My error looks as follows:
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.40 and higher.
The following dependencies do not satisfy the required version:
project ':google_api_headers' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.31`

IDE:
`Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64`

With the following project level gradle content:
`ext.kotlin_version = '1.5.21'`
...
`dependencies {
        classpath 'com.android.tools.build:gradle:7.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }`

**Comment by H-Zaman** [comment]
i just ran into the same issue

**Comment by hoc081098** [comment]
Check my PR https://github.com/zeshuaro/google_api_headers/pull/42

**Comment by zeshuaro** [comment]
I just released `v1.1.1` which should address this issue. Feel free to reopen this if there's still issues.

**Comment by Maroo95** [comment]
> I just released `v1.1.1` which should address this issue. Feel free to reopen this if there's still issues.

I just run into this issue.. how to solve it please?

**Comment by ash-hashtag** [comment]
I too ran into this issue

**Comment by zeshuaro** [comment]
Hey @Maroo95 @ash-hashtag, would either of you be able to share the following:

1. If you're running the latest version of `google_api_headers` plugin?
2. Your `flutter doctor -v` output?
