### ISSUE TITLE
[Question / Security Issue] Security Issue with spoofed headers?

### ISSUE THREAD

**Issue by divick-vama** [zeshuaro/google_api_headers#494]
Hi, asking question here that what prevents someone from spoofing the header with another app's fingerprint for certificate and package name? Wouldn't that allow access to the api by anyone (assuming someone know the packagename, key and certificate fingerprint)?

**Comment by zeshuaro** [comment]
This is how Google has implemented the functionality, so it's more of a question for Google instead.
