### ISSUE TITLE
[BUG] Cannot build on Flutter 3.27

### ISSUE THREAD

**Issue by bsz0206** [zeshuaro/google_api_headers#551]
### Steps to Reproduce

1.  Build the app. you will get the following and the builds fails:

### Expected behaviour

should build

### Actual behaviour

Package google_api_headers:ios references google_api_headers:ios as the default plugin, but it does not provide an inline implementation.
Ask the maintainers of google_api_headers to either avoid referencing a default implementation via `platforms: ios: default_package: google_api_headers` or add an inline implementation to google_api_headers via `platforms: ios:` `pluginClass` or `dartPluginClass`.

### Flutter doctor output

[√] Flutter (Channel stable, 3.27.0, on Microsoft Windows [Version 10.0.22631.4602], locale en-CA)
    • Flutter version 3.27.0 on channel stable at C:\Users\behra\flutter\3.27
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (6 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\behra\AppData\Local\Android\sdk
    • Platform android-35, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\behra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.103.20241202

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by zeshuaro** [comment]
This should have been addressed in v4.3.0, can you confirm which version you're using for the `google_api_headers` package?
