### ISSUE TITLE
problem on GoogleApiHeadersPlugin: Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by alexodus** [zeshuaro/google_api_headers#56]
I have this problem:

`[/Users/<user>/.pub-cache/hosted/pub.dartlang.org/google_api_headers-1.2.0/android/src/main/kotlin/io/github/zeshuaro/google_api_headers/GoogleApiHeadersPlugin.kt](): (58, 68): Type mismatch: inferred type is String? but String was expected`

[✓] Flutter (Channel beta, 2.12.0-4.1.pre, on macOS 12.3 21E230 darwin-arm, locale it-IT)
    • Flutter version 2.12.0-4.1.pre at /Users/alex/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 680962aa75 (4 days ago), 2022-03-16 13:46:03 -0700
    • Engine revision e9f57b5d0f
    • Dart version 2.17.0 (build 2.17.0-182.1.beta)
    • DevTools version 2.11.1

**Comment by zeshuaro** [comment]
Hey @alexodus, thanks for raising this issue. I think I know what the problem is from your error message. I'm just trying to reproduce it myself but wasn't able to. Would you be able to:

1. Share the full `flutter doctor -v` output?
2. Try using the Flutter stable version, i.e. `2.10.3`, and see if the error persists?

**Comment by Dararii** [comment]
Same issue here. Occur with Flutter version 2.12.0-4.1.pre
No problem with 2.10.3

> [✓] Flutter (Channel beta, 2.12.0-4.1.pre, on macOS 12.3 21E230 darwin-arm, locale en-ID)
>     • Flutter version 2.12.0-4.1.pre at /Users/dararii/Dev/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 680962aa75 (5 days ago), 2022-03-16 13:46:03 -0700
>     • Engine revision e9f57b5d0f
>     • Dart version 2.17.0 (build 2.17.0-182.1.beta)
>     • DevTools version 2.11.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
>     • Android SDK at /Users/dararii/Library/Android/sdk
>     • Platform android-32, build-tools 32.0.0
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.3)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • CHROME_EXECUTABLE = /Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge
> 
> [✓] Android Studio (version 2021.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
> 
> [✓] VS Code (version 1.65.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.36.0
> 
> [✓] Connected device (1 available)
>     • Chrome (web) • chrome • web-javascript • Microsoft Edge 99.0.1150.46
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!

**Comment by Dararii** [comment]
Solved it by modifying the error file located at google_api_headers-1.2.0/android/src/main/kotlin/io/github/zeshuaro/google_api_headers/GoogleApiHeadersPlugin.kt

From "call.arguments<String>()" to "call.arguments<String>() as String"

**Comment by zeshuaro** [comment]
Thanks for sharing the extra info and testing on this. Looks like the issue is introduced in the beta channel then and the stable channel is not affected.

Generally stable releases of packages only support the stable releases of Flutter. I'll create a pre-release version of the package to address this issue.

**Comment by emmett-deen** [comment]
@zeshuaro I went ahead and opened a PR, let me know what changes I need to make to pass your checks.

**Comment by zeshuaro** [comment]
I've just release `1.3.0-dev.0` to address this issue. Feel free to re-open this issue if the error still persists.
