### ISSUE TITLE
Flutter 3 support

### ISSUE THREAD

**Issue by mohamadhadibi** [zeshuaro/google_api_headers#79]
please update package package_info_plus to 1.4.2 for flutter 3 support.
thanks.

**Comment by zeshuaro** [comment]
Hey @mohamadhadibi, thanks for raising the issue. This package already supports Flutter 3. Would you be able to share the errors that you are facing?

I don't see anything from the changelog of `package_info_plus` about needing to use 1.4.2 for Flutter 3 support. Also, in the pubspec file, it's defined with `package_info_plus: ^1.4.0` in this package, so it shouldn't be blocking you from installing the latest version anyway.
